name: CI
on:
  - push
  - pull_request

permissions: {}

jobs:
  test:
    name: Test for ${{ matrix.platform.container || matrix.platform.os }} ${{ matrix.platform.target-arch }}, Node.js ${{ matrix.node-version }}
    timeout-minutes: 10
    runs-on: ${{ matrix.platform.os }}
    container: ${{ matrix.platform.container }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20]
        platform:
          [
            {os: ubuntu-latest},
            {os: ubuntu-latest, container: 'alpine:latest'},
            {os: macos-latest, target-arch: x64},
            {os: [self-hosted, macOS, arm64], target-arch: arm64},
            {os: windows-latest, target-arch: x86},
            {os: windows-latest, target-arch: x64},
          ]

    steps:
      - name: Set git to use LF line endings
        if: contains(matrix.platform.os, 'windows')
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.platform.target-arch }}
          cache: 'pnpm'

      - name: Print versions
        run: |
          node --version
          pnpm --version
          node -p "process.platform + '@' + process.arch"

      - name: Install dependencies
        run: pnpm install

      - name: Format
        run: pnpm format:check

      - name: Prebuild
        run: pnpm -r prebuild

      - name: Build
        run: pnpm -r build

      - name: Test
        run: pnpm -r test
